services:
  - type: web
    name: kosmetika
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
